window.monitorData = {
    "news":  [
                 {
                     "url":  "https://www.infobae.com/peru/2026/06/11/cisterna-de-la-municipalidad-de-jesus-maria-lanza-agua-a-simpatizantes-de-roberto-sanchez-acampados-frente-al-jne/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Cisterna de la Municipalidad de Jesús María lanza agua a simpatizantes de Roberto Sánchez acampados frente al JNE - Infobae",
                     "source":  "Infobae",
                     "published_date":  "2026-06-10T20:39:00",
                     "summary":  "Cisterna de la Municipalidad de Jesús María lanza agua a simpatizantes de Roberto Sánchez acampados frente al JNE\u0026nbsp;\u0026nbsp;Infobae",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.infobae.com/resizer/v2/Z4AN3ULYDNE7VEHQ3NWEKRFUSI.jpg?auth=04d674fa94d89896d7b4ee8114d5eb2ac25529a1c24e3552d7091ce66de32f11\u0026smart=true\u0026width=1200\u0026height=630\u0026quality=85",
                     "scraped_at":  "2026-06-12T10:39:10"
                 },
                 {
                     "url":  "https://larepublica.pe/sociedad/2026/06/11/cisternas-de-jesus-maria-mojan-a-manifestantes-de-jp-en-parque-y-municipio-responde-no-es-un-tema-politico-252340",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Cisternas de Jesús María mojan a manifestantes de JP en parque y municipio responde: “No es un tema político” - La República",
                     "source":  "La República",
                     "published_date":  "2026-06-11T14:50:34",
                     "summary":  "Cisternas de Jesús María mojan a manifestantes de JP en parque y municipio responde: “No es un tema político”\u0026nbsp;\u0026nbsp;La República",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://imgmedia.larepublica.pe/1200x735/larepublica/original/2026/06/11/6a2ad505aa36ee290905afa7.jpg",
                     "scraped_at":  "2026-06-12T10:39:11"
                 },
                 {
                     "url":  "https://www.apnoticias.pe/video/municipalidad-de-jesus-maria-se-disculpa-por-incidente-que-afecto-a-manifestantes-de-jp-583509",
                     "query":  "municipalidad de jesus maria",
                     "title":  "🔴🔵 Municipalidad de Jesús María se disculpa por incidente que afectó a manifestantes de JP - apnoticias.pe",
                     "source":  "apnoticias.pe",
                     "published_date":  "2026-06-11T16:53:12",
                     "summary":  "🔴🔵 Municipalidad de Jesús María se disculpa por incidente que afectó a manifestantes de JP\u0026nbsp;\u0026nbsp;apnoticias.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://i3.ytimg.com/vi/VFMtBFDW1ys/hqdefault.jpg",
                     "scraped_at":  "2026-06-12T10:39:13"
                 },
                 {
                     "url":  "https://rpp.pe/politica/elecciones/simpatizantes-de-roberto-sanchez-que-acampan-en-exteriores-de-jne-evaluan-denunciar-a-alcalde-de-jesus-maria-noticia-1692725",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Simpatizantes de Roberto Sánchez que acampan en exteriores de JNE evalúan denunciar a alcalde de Jesús María - RPP",
                     "source":  "RPP",
                     "published_date":  "2026-06-12T08:08:29",
                     "summary":  "Simpatizantes de Roberto Sánchez que acampan en exteriores de JNE evalúan denunciar a alcalde de Jesús María\u0026nbsp;\u0026nbsp;RPP",
                     "sentiment":  "negativo",
                     "sentiment_score":  -1,
                     "relevance":  1,
                     "image_url":  "https://f.rpp-noticias.io/2026/06/12/p-2026-06-12-07-03-01-10680-1877326mp4_1877327.jpg?width=860\u0026quality=80",
                     "scraped_at":  "2026-06-12T10:39:15"
                 },
                 {
                     "url":  "https://gestion.pe/peru/segunda-vuelta-jesus-maria-responde-a-quejas-de-simpatizantes-politicos-que-fueron-desplazados-de-exteriores-de-la-jne-dijo-no-fue-de-indole-politico-noticia/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Jesús María sobre simpatizantes políticos que fueron desplazados de exteriores de la JNE - gestion.pe",
                     "source":  "gestion.pe",
                     "published_date":  "2026-06-11T12:10:22",
                     "summary":  "Jesús María sobre simpatizantes políticos que fueron desplazados de exteriores de la JNE\u0026nbsp;\u0026nbsp;gestion.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://gestion.pe/resizer/v2/JN53ZNNEH5GUVG3PAPP5SMEK3E.jpg?auth=393a7492c59517da620324316e94125633096f0f5e919e449a96731caf5c01ab\u0026width=980\u0026height=528\u0026quality=75\u0026smart=true",
                     "scraped_at":  "2026-06-12T10:39:16"
                 },
                 {
                     "url":  "https://www.atv.pe/noticia/manifestantes-mojados-cisterna-jesus-maria-jne/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Manifestantes que acamparon frente al JNE fueron mojados por cisterna del municipio de Jesús María - ATV.pe",
                     "source":  "ATV.pe",
                     "published_date":  "2026-06-10T22:04:06",
                     "summary":  "Manifestantes que acamparon frente al JNE fueron mojados por cisterna del municipio de Jesús María\u0026nbsp;\u0026nbsp;ATV.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://alba-pe-atv.cdn.mediatiquepress.com/wp-content/uploads/2026/06/manifestantes-mojados-jesus-maria.jpg.jpeg",
                     "scraped_at":  "2026-06-12T10:39:18"
                 },
                 {
                     "url":  "https://www.exitosanoticias.pe/actualidad/municipio-jesus-maria-disculpa-manifestantes-jp-tras-rociarles-agua-frontis-jne-n177559",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Municipio de Jesús María se disculpa con manifestantes de JP tras rociarles agua en el frontis del JNE - Exitosa Noticias",
                     "source":  "Exitosa Noticias",
                     "published_date":  "2026-06-11T10:40:00",
                     "summary":  "Municipio de Jesús María se disculpa con manifestantes de JP tras rociarles agua en el frontis del JNE\u0026nbsp;\u0026nbsp;Exitosa Noticias",
                     "sentiment":  "positivo",
                     "sentiment_score":  1,
                     "relevance":  1,
                     "image_url":  "https://statics.exitosanoticias.pe/2026/06/6a2aedc7b023a.jpg",
                     "scraped_at":  "2026-06-12T10:39:20"
                 },
                 {
                     "url":  "https://caretas.pe/sociedad/fiscalia-investiga-caso-de-cisterna-frente-al-jne-y-partidarios-de-roberto-sanchez-anuncian-acciones-contra-alcalde-de-jesus-maria/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Fiscalía investiga caso de cisterna frente al JNE y partidarios de Roberto Sánchez anuncian acciones contra alcalde de Jesús María - Revista Caretas",
                     "source":  "Revista Caretas",
                     "published_date":  "2026-06-12T10:33:03",
                     "summary":  "Fiscalía investiga caso de cisterna frente al JNE y partidarios de Roberto Sánchez anuncian acciones contra alcalde de Jesús María\u0026nbsp;\u0026nbsp;Revista Caretas",
                     "sentiment":  "negativo",
                     "sentiment_score":  -1,
                     "relevance":  1,
                     "image_url":  "https://caretas.pe/wp-content/uploads/2026/06/HKfIqz8WMAAVH2q.jpeg",
                     "scraped_at":  "2026-06-12T10:39:22"
                 },
                 {
                     "url":  "https://www.peruinforma.com/municipalidad-de-jesus-maria-afirmo-que-el-riego-del-parque-ocupado-por-partidarios-de-roberto-sanchez-fue-por-mantenimiento-programado/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Municipalidad de Jesús María afirmó que el riego del parque ocupado por partidarios de Roberto Sánchez fue por mantenimiento programado - Perú Informa",
                     "source":  "Perú Informa",
                     "published_date":  "2026-06-10T02:00:00",
                     "summary":  "Municipalidad de Jesús María afirmó que el riego del parque ocupado por partidarios de Roberto Sánchez fue por mantenimiento programado\u0026nbsp;\u0026nbsp;Perú Informa",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.peruinforma.com/wp-content/uploads/2026/06/JesusMariaDefensoriaJP.jpg",
                     "scraped_at":  "2026-06-12T10:39:23"
                 },
                 {
                     "url":  "https://peru21.pe/lima/campo-de-marte-municipalidad-de-jesus-maria-retomara-el-control-de-areas-verdes/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Campo de Marte: Municipalidad de Jesús María retomará el control de áreas verdes - Perú 21",
                     "source":  "Perú 21",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Campo de Marte: Municipalidad de Jesús María retomará el control de áreas verdes\u0026nbsp;\u0026nbsp;Perú 21",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://images.unsplash.com/photo-1450133064473-71024230f91b?auto=format\u0026fit=crop\u0026w=600\u0026q=80",
                     "scraped_at":  "2026-06-12T10:39:25"
                 },
                 {
                     "url":  "https://www.infobae.com/peru/2026/06/11/municipalidad-de-jesus-maria-justifica-riego-en-parque-donde-permanecian-simpatizantes-de-de-roberto-sanchez/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Municipalidad de Jesús María justifica riego en parque donde permanecían simpatizantes de de Roberto Sánchez - Infobae",
                     "source":  "Infobae",
                     "published_date":  "2026-06-11T08:09:00",
                     "summary":  "Municipalidad de Jesús María justifica riego en parque donde permanecían simpatizantes de de Roberto Sánchez\u0026nbsp;\u0026nbsp;Infobae",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.infobae.com/resizer/v2/Z4PIRMTUNNDLBIVLB5ORLBP5SA.png?auth=b03aa9da3acd96588a6e7d8ac521fe80f27347fc8d4bd9fa10a7451c1e15f4a0\u0026smart=true\u0026width=1200\u0026height=630\u0026quality=85",
                     "scraped_at":  "2026-06-12T10:39:27"
                 },
                 {
                     "url":  "https://www.apnoticias.pe/video/cisterna-de-municipalidad-de-jesus-maria-lanza-agua-a-simpatizantes-de-jp-frente-a-jne-tlr-583254",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Cisterna de Municipalidad de Jesús María lanza agua a simpatizantes de JP frente a JNE #tlr - apnoticias.pe",
                     "source":  "apnoticias.pe",
                     "published_date":  "2026-06-10T21:28:15",
                     "summary":  "Cisterna de Municipalidad de Jesús María lanza agua a simpatizantes de JP frente a JNE #tlr\u0026nbsp;\u0026nbsp;apnoticias.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://i1.ytimg.com/vi/hGzyIIQLeo8/hqdefault.jpg",
                     "scraped_at":  "2026-06-12T10:39:28"
                 },
                 {
                     "url":  "https://www.atv.pe/noticia/josue-gutierrez-exige-respuesta-manifestantes-mojados-jesus-maria/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Josué Gutiérrez por simpatizantes de JP mojados: \"Exigimos una respuesta de Jesús María. No se puede provocar a la población\" - ATV.pe",
                     "source":  "ATV.pe",
                     "published_date":  "2026-06-10T22:23:53",
                     "summary":  "Josué Gutiérrez por simpatizantes de JP mojados: \"Exigimos una respuesta de Jesús María. No se puede provocar a la población\"\u0026nbsp;\u0026nbsp;ATV.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://alba-pe-atv.cdn.mediatiquepress.com/wp-content/uploads/2026/06/defensor-del-pueblo-manifestantes-mojados.jpg.jpeg",
                     "scraped_at":  "2026-06-12T10:39:30"
                 },
                 {
                     "url":  "https://www.infobae.com/peru/2026/05/22/alcalde-de-jesus-maria-sobre-obras-inconclusas-en-campo-de-marte-no-vamos-a-poner-en-riesgo-este-pulmon-ecologico/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Alcalde de Jesús María sobre obras inconclusas en Campo de Marte: “No vamos a poner en riesgo este pulmón ecológico” - Infobae",
                     "source":  "Infobae",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Alcalde de Jesús María sobre obras inconclusas en Campo de Marte: “No vamos a poner en riesgo este pulmón ecológico”\u0026nbsp;\u0026nbsp;Infobae",
                     "sentiment":  "positivo",
                     "sentiment_score":  1,
                     "relevance":  1,
                     "image_url":  "https://www.infobae.com/resizer/v2/R4SUE2MZLRCSZBAL74VIML2OGE.png?auth=2e1441fa4e6839d3a74083c3f55a50ed3838f02c6bb93be730c9f617d0bcf4ae\u0026smart=true\u0026width=1200\u0026height=630\u0026quality=85",
                     "scraped_at":  "2026-06-12T10:39:32"
                 },
                 {
                     "url":  "https://www.infobae.com/peru/2026/05/22/recuperacion-del-campo-de-marte-tiene-nueva-fecha-de-entrega-y-sus-areas-verdes-estaran-a-cargo-de-jesus-maria/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Recuperación del Campo de Marte tiene nueva fecha de entrega y sus areas verdes estarán a cargo de Jesús María - Infobae",
                     "source":  "Infobae",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Recuperación del Campo de Marte tiene nueva fecha de entrega y sus areas verdes estarán a cargo de Jesús María\u0026nbsp;\u0026nbsp;Infobae",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.infobae.com/resizer/v2/TIC6D3ULEFFRFHYDWALFQSY6TE.jpg?auth=4277f021147161ec0adc50474eb2d887b1049a52260b2719efe63319f9eae17f\u0026smart=true\u0026width=1200\u0026height=630\u0026quality=85",
                     "scraped_at":  "2026-06-12T10:39:33"
                 },
                 {
                     "url":  "https://gestion.pe/peru/campo-de-marte-de-jesus-maria-municipalidad-de-lima-resolvio-contrato-por-abandono-de-obras-noticia/",
                     "query":  "municipalidad de jesus maria",
                     "title":  "Campo de Marte en Jesús María: Municipalidad de Lima rescindió contrato por abandono de obras - gestion.pe",
                     "source":  "gestion.pe",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Campo de Marte en Jesús María: Municipalidad de Lima rescindió contrato por abandono de obras\u0026nbsp;\u0026nbsp;gestion.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://gestion.pe/resizer/v2/4KL54ZZTVVBADBHVDG6RHB45LM.jpg?auth=58fcc00f6e45fb72aad033fc87fa25481076bd4657ac4f1d1c98231cc7a36ba5\u0026width=980\u0026height=528\u0026quality=75\u0026smart=true",
                     "scraped_at":  "2026-06-12T10:39:35"
                 },
                 {
                     "url":  "https://www.jesusmaria.gov.ar/noticias/ciudad/la-municipalidad-de-jesus-maria-ofrece-nuevos-talleres-gratuitos-de-tecnologia-para-vecinos.html",
                     "query":  "municipalidad de jesus maria",
                     "title":  "La Municipalidad de Jesús María ofrece nuevos talleres gratuitos de tecnología para vecinos - jesusmaria.gov.ar",
                     "source":  "jesusmaria.gov.ar",
                     "published_date":  "2026-03-04T10:25:49",
                     "summary":  "La Municipalidad de Jesús María ofrece nuevos talleres gratuitos de tecnología para vecinos\u0026nbsp;\u0026nbsp;jesusmaria.gov.ar",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.jesusmaria.gov.ar/frontend/images/preview_meta.jpg",
                     "scraped_at":  "2026-06-12T10:39:37"
                 },
                 {
                     "url":  "https://elpopular.pe/espectaculos/2026/02/16/quien-es-sebastian-galvez-hombre-ampayado-con-laura-spoya-que-se-llevo-sus-cosas-y-que-tiene-que-ver-con-la-alcaldia-de-jesus-maria-404768",
                     "query":  "jesús gálvez jesus maria",
                     "title":  "¿Quién es Sebastián Gálvez, hombre \u0027AMPAYADO\u0027 con Laura Spoya que se LLEVÓ sus cosas, y qué tiene que ver con la alcaldía de Jesús María? - El Popular",
                     "source":  "El Popular",
                     "published_date":  "2026-02-16T03:00:00",
                     "summary":  "¿Quién es Sebastián Gálvez, hombre \u0027AMPAYADO\u0027 con Laura Spoya que se LLEVÓ sus cosas, y qué tiene que ver con la alcaldía de Jesús María?\u0026nbsp;\u0026nbsp;El Popular",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://elpopular.cronosmedia.glr.pe/original/2026/02/16/69934a7c91907deb33014514.jpg",
                     "scraped_at":  "2026-06-12T10:39:39"
                 },
                 {
                     "url":  "https://www.facebook.com/Exitosanoticias/posts/-harry-mac-bride-gerente-municipal-de-jes%C3%BAs-mar%C3%ADa-se-disculp%C3%B3-a-trav%C3%A9s-de-exitos/1456102716552782/",
                     "query":  "alcalde jesus maria",
                     "title":  "🔴🔵 Harry Mac Bride, gerente municipal de Jesús María, se disculpó a través de Exitosa por el incidente en el que se mojó a manifestantes de Juntos por el Perú que acampaban en exteriores del Jurado Nacional de Elecciones. Además, explicó que previo a l - facebook.com",
                     "source":  "facebook.com",
                     "published_date":  "2026-06-12T00:10:51",
                     "summary":  "🔴🔵 Harry Mac Bride, gerente municipal de Jesús María, se disculpó a través de Exitosa por el incidente en el que se mojó a manifestantes de Juntos por el Perú que acampaban en exteriores del Jurado Nacional de Elecciones. Además, explicó que previo a l\u0026nbsp;\u0026nbsp;facebook.com",
                     "sentiment":  "positivo",
                     "sentiment_score":  1,
                     "relevance":  1,
                     "image_url":  "https://images.unsplash.com/photo-1504711434969-e33886168f5c?auto=format\u0026fit=crop\u0026w=600\u0026q=80",
                     "scraped_at":  "2026-06-12T10:39:41"
                 },
                 {
                     "url":  "https://diariocorreo.pe/politica/simpatizantes-de-roberto-sanchez-denunciarian-a-alcalde-de-jesus-maria-tras-intervencion-con-cisterna-noticia/",
                     "query":  "alcalde jesus maria",
                     "title":  "Simpatizantes de Roberto Sánchez denunciarían a alcalde de Jesús María tras intervención con cisterna - Diario Correo",
                     "source":  "Diario Correo",
                     "published_date":  "2026-06-12T09:54:20",
                     "summary":  "Simpatizantes de Roberto Sánchez denunciarían a alcalde de Jesús María tras intervención con cisterna\u0026nbsp;\u0026nbsp;Diario Correo",
                     "sentiment":  "negativo",
                     "sentiment_score":  -1,
                     "relevance":  1,
                     "image_url":  "https://diariocorreo.pe/resizer/v2/W6NSLIZMVFDLXFCUZWPPFHMVNI.jpg?auth=df51b71c5a5221ccb8ad563a1859ac47f9db50f7c66c5c75ab9c57001f457c33\u0026width=980\u0026height=528\u0026quality=75\u0026smart=true",
                     "scraped_at":  "2026-06-12T10:39:43"
                 },
                 {
                     "url":  "https://andina.pe/agencia/noticia-campo-marte-quedara-bajo-mantenimiento-comuna-jesus-maria-1076249.aspx",
                     "query":  "alcalde jesus maria",
                     "title":  "Campo de Marte quedará bajo mantenimiento de comuna de Jesús María - Agencia Peruana de Noticias | ANDINA",
                     "source":  "Agencia Peruana de Noticias | ANDINA",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Campo de Marte quedará bajo mantenimiento de comuna de Jesús María\u0026nbsp;\u0026nbsp;Agencia Peruana de Noticias | ANDINA",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://portal.andina.pe/EDPfotografia3/Thumbnail/2026/02/23/001255867W.webp",
                     "scraped_at":  "2026-06-12T10:39:44"
                 },
                 {
                     "url":  "https://diariocorreo.pe/edicion/lima/alcalde-de-jesus-maria-preve-que-obras-del-campo-de-marte-culminen-en-septiembre-noticia/",
                     "query":  "alcalde jesus maria",
                     "title":  "Alcalde de Jesús María prevé que obras del Campo de Marte culminen en septiembre - Diario Correo",
                     "source":  "Diario Correo",
                     "published_date":  "2026-05-22T02:00:00",
                     "summary":  "Alcalde de Jesús María prevé que obras del Campo de Marte culminen en septiembre\u0026nbsp;\u0026nbsp;Diario Correo",
                     "sentiment":  "positivo",
                     "sentiment_score":  1,
                     "relevance":  1,
                     "image_url":  "https://diariocorreo.pe/resizer/v2/ESIA7PFVXZEKBOZ44W2KDGYOEY.png?auth=32c3a86fe8134593235fa35386a6b0081353a743214823a82cc4e55c6a44a991\u0026width=980\u0026height=528\u0026quality=75\u0026smart=true",
                     "scraped_at":  "2026-06-12T10:39:46"
                 },
                 {
                     "url":  "https://imasolu.com/encuesta-politica-2026-como-se-evalua-la-gestion-municipal-en-jesus-maria-enero-2026/",
                     "query":  "alcalde jesus maria",
                     "title":  "ENCUESTA POLÍTICA 2026: ¿CÓMO SE EVALÚA LA GESTIÓN MUNICIPAL EN JESÚS MARÍA? | ENERO 2026 - Imasolu",
                     "source":  "Imasolu",
                     "published_date":  "2026-01-29T03:00:00",
                     "summary":  "ENCUESTA POLÍTICA 2026: ¿CÓMO SE EVALÚA LA GESTIÓN MUNICIPAL EN JESÚS MARÍA? | ENERO 2026\u0026nbsp;\u0026nbsp;Imasolu",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://imasolu.com/wp-content/uploads/2026/01/Aprobacion-alcalde-de-Jesus-Maria-scaled.jpg",
                     "scraped_at":  "2026-06-12T10:39:48"
                 },
                 {
                     "url":  "https://www.atv.pe/noticia/vecinos-jesus-maria-exigen-puesto-salud/",
                     "query":  "alcalde jesus maria",
                     "title":  "Vecinos de Jesús María exigen construcción de puesto de salud tras 3 gobiernos sin avances - ATV.pe",
                     "source":  "ATV.pe",
                     "published_date":  "2026-05-04T02:00:00",
                     "summary":  "Vecinos de Jesús María exigen construcción de puesto de salud tras 3 gobiernos sin avances\u0026nbsp;\u0026nbsp;ATV.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://alba-pe-atv.cdn.mediatiquepress.com/wp-content/uploads/2026/05/protesta-vecinos-puesto-salud-jesus-maria.jpg",
                     "scraped_at":  "2026-06-12T10:39:49"
                 },
                 {
                     "url":  "https://www.apnoticias.pe/jesus-maria-inicia-renovacion-de-parques-y-alamedas-para-recuperar-espacios-publicos-1501276",
                     "query":  "alcalde jesus maria",
                     "title":  "Jesús María inicia renovación de parques y alamedas para recuperar espacios públicos - apnoticias.pe",
                     "source":  "apnoticias.pe",
                     "published_date":  "2026-05-14T02:00:00",
                     "summary":  "Jesús María inicia renovación de parques y alamedas para recuperar espacios públicos\u0026nbsp;\u0026nbsp;apnoticias.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://diariouno.pe/wp-content/uploads/2026/05/WhatsApp-Image-2025-03-19-at-10.26.06-4-scaled-1.jpeg",
                     "scraped_at":  "2026-06-12T10:39:51"
                 },
                 {
                     "url":  "https://www.infobae.com/peru/2026/04/30/vecinos-de-jesus-maria-esperan-desde-hace-50-anos-la-construccion-de-una-posta-de-salud-para-el-distrito/",
                     "query":  "alcalde jesus maria",
                     "title":  "Vecinos de Jesús María esperan desde hace 50 años la construcción de una posta de salud para el distrito - Infobae",
                     "source":  "Infobae",
                     "published_date":  "2026-04-30T02:00:00",
                     "summary":  "Vecinos de Jesús María esperan desde hace 50 años la construcción de una posta de salud para el distrito\u0026nbsp;\u0026nbsp;Infobae",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://www.infobae.com/resizer/v2/2EWOHW4K2ZC2LKW52B4YWQWQT4.jpg?auth=0d18e49a0fc263a16ae4dfe89b5c85d42cdee4e8f5d120fbf4d22c133c130252\u0026smart=true\u0026width=1200\u0026height=630\u0026quality=85",
                     "scraped_at":  "2026-06-12T10:39:53"
                 },
                 {
                     "url":  "https://panamericana.pe/buenosdiasperu/locales/468250-jesus-maria-vecinos-exigen-posta-medica-prometieron-50-anos",
                     "query":  "alcalde jesus maria",
                     "title":  "Jesús María: vecinos exigen posta médica que... - Panamericana TV",
                     "source":  "Panamericana TV",
                     "published_date":  "2026-04-30T02:00:00",
                     "summary":  "Jesús María: vecinos exigen posta médica que...\u0026nbsp;\u0026nbsp;Panamericana TV",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://s3.amazonaws.com/imagenespantv/noticia/2026/04/orig-1777561884130.jpg",
                     "scraped_at":  "2026-06-12T10:39:54"
                 },
                 {
                     "url":  "https://diariouno.pe/2026/05/14/drones-vigilaran-colegios-de-jesus-maria/",
                     "query":  "alcalde jesus maria",
                     "title":  "Drones vigilarán colegios de Jesús María - diariouno.pe",
                     "source":  "diariouno.pe",
                     "published_date":  "2026-05-14T02:00:00",
                     "summary":  "Drones vigilarán colegios de Jesús María\u0026nbsp;\u0026nbsp;diariouno.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://diariouno.pe/wp-content/uploads/2026/05/604696910_1149432677405657_8903063021651600160_n.jpg",
                     "scraped_at":  "2026-06-12T10:39:56"
                 },
                 {
                     "url":  "https://diariocorreo.pe/politica/simpatizantes-de-roberto-sanchez-denunciarian-a-alcalde-de-jesus-maria-tras-intervencion-con-cisterna-noticia/?outputType=amp",
                     "query":  "alcalde jesus maria",
                     "title":  "Simpatizantes de Roberto Sánchez denunciarían a alcalde de Jesús María tras intervención con cisterna - Diario Correo",
                     "source":  "Diario Correo",
                     "published_date":  "2026-06-12T09:54:20",
                     "summary":  "Simpatizantes de Roberto Sánchez denunciarían a alcalde de Jesús María tras intervención con cisterna\u0026nbsp;\u0026nbsp;Diario Correo",
                     "sentiment":  "negativo",
                     "sentiment_score":  -1,
                     "relevance":  1,
                     "image_url":  "https://diariocorreo.pe/resizer/v2/W6NSLIZMVFDLXFCUZWPPFHMVNI.jpg?auth=df51b71c5a5221ccb8ad563a1859ac47f9db50f7c66c5c75ab9c57001f457c33\u0026width=980\u0026height=528\u0026quality=75\u0026smart=true",
                     "scraped_at":  "2026-06-12T11:22:54"
                 },
                 {
                     "url":  "https://diariouno.pe/2026/05/14/jesus-maria-inicia-renovacion-de-parques-y-alamedas-para-recuperar-espacios-publicos/",
                     "query":  "alcalde jesus maria",
                     "title":  "Jesús María inicia renovación de parques y alamedas para recuperar espacios públicos - diariouno.pe",
                     "source":  "diariouno.pe",
                     "published_date":  "2026-05-14T02:00:00",
                     "summary":  "Jesús María inicia renovación de parques y alamedas para recuperar espacios públicos\u0026nbsp;\u0026nbsp;diariouno.pe",
                     "sentiment":  "neutral",
                     "sentiment_score":  0,
                     "relevance":  1,
                     "image_url":  "https://diariouno.pe/wp-content/uploads/2026/05/WhatsApp-Image-2025-03-19-at-10.26.06-4-scaled-1.jpeg",
                     "scraped_at":  "2026-06-12T11:23:20"
                 }
             ],
    "youtube":  [
                    {
                        "video_id":  "hGzyIIQLeo8",
                        "query":  "municipalidad de jesus maria",
                        "title":  "Cisterna de Municipalidad de Jesús María lanza agua a simpatizantes de JP  frente a JNE #tlr",
                        "channel":  "La República - LR+",
                        "published_date":  "2026-06-10T20:24:10",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: Cisterna de Municipalidad de Jesús María lanza agua a simpatizantes de JP  frente a JNE #tlr",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/hGzyIIQLeo8/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:39:58"
                    },
                    {
                        "video_id":  "VFMtBFDW1ys",
                        "query":  "municipalidad de jesus maria",
                        "title":  "🔴🔵 Municipalidad de Jesús María se disculpa por incidente que afectó a manifestantes de JP",
                        "channel":  "Exitosa Noticias",
                        "published_date":  "2026-06-11T12:37:04",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: 🔴🔵 Municipalidad de Jesús María se disculpa por incidente que afectó a manifestantes de JP",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/VFMtBFDW1ys/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:39:59"
                    },
                    {
                        "video_id":  "YU16fMNF2i8",
                        "query":  "municipalidad de jesus maria",
                        "title":  "Municipalidad de Jesús María reprime a simpatizantes de JP que realizaban vigilia",
                        "channel":  "Wayka",
                        "published_date":  "2026-06-10T17:47:40",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: Municipalidad de Jesús María reprime a simpatizantes de JP que realizaban vigilia",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/YU16fMNF2i8/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:40:00"
                    },
                    {
                        "video_id":  "NgWZwkf6jgA",
                        "query":  "municipalidad de jesus maria",
                        "title":  "Municipalidad de Jesús María baña a los votantes de JP roberto sanchez #fypシ #shorts #robertosanchez",
                        "channel":  "Mariobrawz",
                        "published_date":  "2026-06-10T20:20:53",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: Municipalidad de Jesús María baña a los votantes de JP roberto sanchez #fypシ #shorts #robertosanchez",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/NgWZwkf6jgA/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:40:00"
                    },
                    {
                        "video_id":  "BwEZ413HUbo",
                        "query":  "municipalidad de jesus maria",
                        "title":  "Municipalidad de Jesús María lanzó agua contra manifestantes de Juntos por el Perú.",
                        "channel":  "Jony Clariana \u0026 Abogados",
                        "published_date":  "2026-06-10T19:49:12",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: Municipalidad de Jesús María lanzó agua contra manifestantes de Juntos por el Perú.",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/BwEZ413HUbo/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:40:01"
                    },
                    {
                        "video_id":  "J2HjF0geoj8",
                        "query":  "municipalidad de jesus maria",
                        "title":  "Manifestantes que acamparon frente al JNE fueron mojados por cisterna del municipio de Jesús María",
                        "channel":  "ATV Noticias",
                        "published_date":  "2026-06-10T22:05:34",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: Manifestantes que acamparon frente al JNE fueron mojados por cisterna del municipio de Jesús María",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/J2HjF0geoj8/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T10:40:04"
                    },
                    {
                        "video_id":  "95I_uRKIJ6c",
                        "query":  "municipalidad de jesus maria",
                        "title":  "MUNICIPALIDAD DE JESÚS MARÍA PIDE DISCULPAS A MANIFESTANTES DE JP POR ROCIARLES AGUA #shorts #lr",
                        "channel":  "La República - LR+",
                        "published_date":  "2026-06-12T11:06:54",
                        "description":  "Video monitoreado de YouTube.",
                        "transcript_snippet":  "Menciones detectadas en el video: MUNICIPALIDAD DE JESÚS MARÍA PIDE DISCULPAS A MANIFESTANTES DE JP POR ROCIARLES AGUA #shorts #lr",
                        "sentiment":  "neutral",
                        "sentiment_score":  0,
                        "relevance":  1,
                        "image_url":  "https://img.youtube.com/vi/95I_uRKIJ6c/hqdefault.jpg",
                        "scraped_at":  "2026-06-12T11:23:33"
                    }
                ],
    "updated_at":  "2026-06-12T11:23:51"
};
